### ISSUE TITLE
UNet training returns ValueError shape mismatch

### ISSUE THREAD

**Issue by shebna12** [DIAGNijmegen/picai_baseline#51]
I followed the general guide and the model-specific guide but I encountered a problem on the [UNet training part](https://github.com/DIAGNijmegen/picai_baseline/blob/main/unet_baseline.md#u-net---training-and-cross-validation). I am running the code in Google Colab. I've tried implementing the [bugfix PR ](https://github.com/DIAGNijmegen/picai_baseline/pull/50) but the error remains the same. Below is a code snippet of the error:
```GPUs: Tesla V100-SXM2-16GB
CPU Threads: 4
Dataset Definition: --------------------------------------------------------------------------------
Fold Number: 0
Data Classes: [0.0, 2.0, 3.0, 4.0, 5.0]
Train-Time Class Weights: [0.46153846 0.53846154]
Training Samples [-:140;+:120]: 260
Validation Samples [-:140;+:120]: 260
Traceback (most recent call last):
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/train.py", line 161, in <module>
    main()
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/train.py", line 99, in main
    train_gen, valid_gen, class_weights = prepare_datagens(args=args, fold_id=f)
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/training_setup/data_generator.py", line 108, in prepare_datagens
    data_pair = monai.utils.misc.first(check_loader)
  File "/usr/local/lib/python3.10/dist-packages/monai/utils/misc.py", line 116, in first
    for i in iterable:
  File "/usr/local/lib/python3.10/dist-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/training_setup/data_generator.py", line 72, in generate_train_batch
    return self.collate_fn(batch)
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/training_setup/data_generator.py", line 40, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/training_setup/data_generator.py", line 40, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/training_setup/data_generator.py", line 32, in default_collate
    return np.vstack(batch)
  File "<__array_function__ internals>", line 180, in vstack
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 21 and the array at index 2 has size 19
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-6-6e18c76e07c0>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('shell', '', "python -u  /content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/train.py \\\n  --weights_dir='/content/drive/MyDrive/300/workdir/UNet/weights/' \\\n  --overviews_dir='/content/drive/MyDrive/300/workdir/results/UNet/overviews/Task2201_picai_baseline' \\\n  --folds 0 --max_threads 4 --enable_da 0 --num_epochs 2 \\\n  --validate_n_epochs 1 --validate_min_epoch 0\n")

3 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'python -u  /content/drive/MyDrive/300/picai_baseline/src/picai_baseline/unet/train.py \
  --weights_dir='/content/drive/MyDrive/300/workdir/UNet/weights/' \
  --overviews_dir='/content/drive/MyDrive/300/workdir/results/UNet/overviews/Task2201_picai_baseline' \
  --folds 0 --max_threads 4 --enable_da 0 --num_epochs 2 \
  --validate_n_epochs 1 --validate_min_epoch 0
' returned non-zero exit status 1.```

**Comment by joeranbosma** [comment]
Hi @shebna12,

It seems that your data preparation was done without the U-Net-specific resampling requirements: https://github.com/DIAGNijmegen/picai_baseline/blob/main/unet_baseline.md#u-net---data-preparation. Please run the data preparation again with the spacing and matrix size, for example:

```
python prepare_data_semi_supervised.py --spacing 3.0 0.5 0.5 --matrix_size 20 256 256
```

**Comment by shebna12** [comment]
Hi @joeranbosma !

I followed the changes in the updated [documentation](https://github.com/DIAGNijmegen/picai_baseline/pull/52) and it's working as expected now. Thanks!
