### ISSUE TITLE
Unet train error at focal.py

### ISSUE THREAD

**Issue by MuhammedPesen** [DIAGNijmegen/picai_baseline#53]
Hello,
I followed the guide but I got stuck at the UNet train part. 
```py
Traceback (most recent call last):
  File "/home/usr/projects/bitirme/Codes/picai_baseline/src/picai_baseline/unet/train.py", line 161, in <module>
    main()
  File "/home/usr/projects/bitirme/Codes/picai_baseline/src/picai_baseline/unet/train.py", line 134, in main
    model, optimizer, train_gen, tracking_metrics, writer = optimize_model(
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/picai_baseline/unet/training_setup/callbacks.py", line 119, in optimize_model
    loss = loss_func(outputs, labels)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/picai_baseline/unet/training_setup/loss_functions/focal.py", line 34, in forward
    targets = F.one_hot(targets, num_classes=self.num_classes).float()
RuntimeError: one_hot is only applicable to index tensor.
```

For debugging I checked the targets dtype and it returned float32. When I converted from float32 to long the issue resolved but now I am getting a new one. 

```py
Traceback (most recent call last):
  File "/home/usr/projects/bitirme/Codes/picai_baseline/src/picai_baseline/unet/train.py", line 161, in <module>
    main()
  File "/home/usr/projects/bitirme/Codes/picai_baseline/src/picai_baseline/unet/train.py", line 134, in main
    model, optimizer, train_gen, tracking_metrics, writer = optimize_model(
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/picai_baseline/unet/training_setup/callbacks.py", line 119, in optimize_model
    loss = loss_func(outputs, labels)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/picai_baseline/unet/training_setup/loss_functions/focal.py", line 37, in forward
    ce_loss = F.binary_cross_entropy(inputs, targets, reduction="none")
  File "/home/usr/miniconda3/envs/demo/lib/python3.9/site-packages/torch/nn/functional.py", line 3113, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([8, 256, 1, 20, 256, 2])) that is different to the input size (torch.Size([8, 2, 20, 256, 256])) is deprecated. Please ensure they have the same size.
```

targets.shape =  torch.Size([8, 1, 20, 256, 256]) 
inputs.shape = torch.Size([8, 2, 20, 256, 256])

**Comment by anindox8** [comment]
Hi @MuhammedPesen, could you also confirm the exact training command (+ arguments) that you used in this step?

**Comment by MuhammedPesen** [comment]
It was my bad. I mistakingly used wrong command which resulted in the images not being resampled. After also applying the bug_fix [https://github.com/DIAGNijmegen/picai_baseline/pull/50](url) the training started without issue.
