### ISSUE TITLE
Error when running `python src/picai_baseline/unet/plan_overview.py`

### ISSUE THREAD

**Issue by Kyfafyd** [DIAGNijmegen/picai_baseline#9]
Hi, thanks for the code!
I meet the following error during running `python src/picai_baseline/unet/plan_overview.py`.
Could you help to figure it out?
```
Preparing fold 0..
Traceback (most recent call last):
  File "src/picai_baseline/unet/plan_overview.py", line 51, in <module>
    lbl = sitk.GetArrayFromImage(sitk.ReadImage(str(preprocessed_data_path / 'labelsTr' / f'{subject_id}.nii.gz')))
  File "/research/d4/gds/zwang21/anaconda3/envs/surgical/lib/python3.8/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/research/d4/gds/zwang21/anaconda3/envs/surgical/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "workdir/nnUNet_raw_data/Task2201_picai_baseline/labelsTr/10133_1000135.nii.gz" does not exist.
```
BTW, I just uncomment the code in `src/picai_baseline/prepare_data.py` like following:
```python
if mha2nnunet_settings_path.exists():
    print(f"Found mha2nnunet settings at {mha2nnunet_settings_path}, skipping..")
else:
    # generate mha2nnunet conversion plan
    Path(mha2nnunet_settings_path.parent).mkdir(parents=True, exist_ok=True)
    generate_mha2nnunet_settings(
        archive_dir=mha_archive_dir,
        annotations_dir=annotations_dir,
        output_path=mha2nnunet_settings_path,
    )

    # read mha2nnunet_settings
    with open(mha2nnunet_settings_path) as fp:
        mha2nnunet_settings = json.load(fp)

    # note: modify preprocessing settings here
    mha2nnunet_settings["preprocessing"]["matrix_size"] = [20, 256, 256]
    mha2nnunet_settings["preprocessing"]["spacing"] = [3.0, 0.5, 0.5]

    # save mha2nnunet_settings
    with open(mha2nnunet_settings_path, "w") as fp:
        json.dump(mha2nnunet_settings, fp, indent=4)
    print(f"Saved mha2nnunet settings to {mha2nnunet_settings_path}")
```

**Comment by joeranbosma** [comment]
Hi @Kyfafyd,

It appears you are missing an annotation (or multiple). Did you run `prepare_data.py` until completion, and did this run without issues? You can run the same script again to check, it will skip over the steps that are already complete.

Your modification of `prepare_data.py` to be used for the U-Net baseline appears correct.

Kind regards,
Joeran
